### ISSUE TITLE
Posts without links have `undefined` as the url

### ISSUE THREAD

**Issue by jacobmischka** [sveltejs/svelte-hackernews#1]
Clicking comments link directly works as it should.

![image](https://cloud.githubusercontent.com/assets/3939997/23600293/91738610-020b-11e7-9f9e-d9f09b709b77.png)

**Comment by Rich-Harris** [comment]
Thanks! Fixed, and added the missing `item.text` that appears under Ask HN posts.

**Comment by jacobmischka** [comment]
Oh oops I didn't even notice that. Thanks!
