### ISSUE TITLE
first load was 5 seconds for https://svelte-hn.now.sh/

### ISSUE THREAD

**Issue by kzc** [sveltejs/svelte-hackernews#2]
...compared to sub second load for hacker news.

Font load time perhaps? Was using Safari 9.

**Comment by kzc** [comment]
Closing. This is a work in progress and performance probably hasn't been looked at.

**Comment by Rich-Harris** [comment]
There's definitely some more we can do (caching would be a start!), but I'm surprised it was as slow as that — it's near instantaneous for me, in NYC. Maybe now.sh had been idle a while and just needed a moment to warm up? Not sure. There's probably all sorts of stuff I'm doing wrong on the back end

**Comment by kzc** [comment]
After initial load Safari 9 takes ~1 second per page view.

Changed browsers to Firefox 51 immediately after Safari when the server VM presumably warmed up. 3 second initial load in Firefox, and sub-second after that. 

Hacker News will be faster presumably because its back end and web server are probably co-located?

**Comment by Rich-Harris** [comment]
> Hacker News will be faster presumably because its back end and web server are probably co-located?

Yes, they definitely have an advantage! Is a very fast site. We could keep all top/new items in memory and avoid any behind-the-scenes network requests, I suppose. Also need to implement some service worker stuff so that you get an app shell straight away then only need to fetch a couple kb of JSON
