### ISSUE TITLE
Looses history state

### ISSUE THREAD

**Issue by zigomir** [sveltejs/svelte-hackernews#9]
If you click on comments link you can go back with browser navigation but then you can't got forward again to get back to the comments.

**Comment by Rich-Harris** [comment]
Ah, looks like that's only happening on the initial load — if you go to e.g. the 'new' tab, then back to 'top', clicking on comments then back then forward works correctly. I suspect it's related to https://github.com/Rich-Harris/roadtrip/commit/d90dd0705f01ad8289b69bdfce833e29a1e7faa8. Thanks for raising this, will look into it when I get a chance

**Comment by Rich-Harris** [comment]
fixed now! thanks again
